##
## EPITECH PROJECT, 2026
## missing_prereq fixture
## File description:
## Makefile dont all depend d un prerequis sans regle
##

all: dep.txt

clean:
	rm -f hello.o

fclean: clean
	rm -f hello

re: fclean all

.PHONY: all clean fclean re
